### PR TITLE
allow for passing global data via the config object

### PR DESCRIPTION
**Pull request by thompsongl**
Adds the ability to pass data via the config object so that it can be used in each file.

I can see a future need for passing a file (just JSON, probably), but this solves the basic need.
Does not support command line use currently, as passing a file would almost certainly be required.
If you'd like to see file-passing and/or command line support implemented before merging, I'd be happy to do so.

### CODE REVIEW

**Comment by gakimball** [comment]
Can you think of a use-case within the Foundation documentation? Not to say that's the only reason the library exists, but that's the *main* reason it exists right now. ;)

**Comment by thompsongl** [comment]
This is definitely outside of what the Foundation docs need. I've noticed a couple other divergences with our project needs, and maintaining a permanent fork might be our best option for now. Once there's more stability on our end, we can reassess.

**Comment by gakimball** [comment]
Ooh! You're using it in your own work? That's exciting :) To be sure, I don't want this to be a ZURB-only library, which is why I wrote it in a way that's adaptable.

I think the reason we don't need the site-level metadata is because we funnel these pages into a proper static site generator with its own Handlebars environment set up. However, it's probably possible to use *only* Supercollider to compile the whole page layout, although you're missing extra features like custom partials.

My main concern is feature creep, but perhaps Supercollider needs to give you more access to Handlebars. You can pass in your own Handlebars instance, but I don't know if you can pass in custom data that way, or just partials and helpers.

**Comment by gakimball** [comment]
Finally merged this! Thanks for the contribution :)

The only change I made was to flip the extend order, so that local variables override global ones.

Found a use-case within Foundation—eventually, all three frameworks will use the template, and we need a way to globally define things like framework name, repo name, etc.

**Comment by gakimball** [comment]
*Aaaaand* doing that flip introduced a bug ;) I love object extends.

**Pull request merged**
